# Application configuration for ShoppingAPI
spring:
  application:
    name: ShoppingAPI  # Name of the Spring Boot application

  datasource:
    url: ${DATASOURCE_URL}  # Database connection URL
    username: ${DATASOURCE_USERNAME}  # Database username
    password: ${DATASOURCE_PASSWORD}  # Database password
    driver-class-name: org.postgresql.Driver  # JDBC driver for PostgreSQL

  jpa:
    hibernate:
      ddl-auto: update  # Hibernate schema update strategy
    show-sql: false  # Show SQL statements in logs
    properties:
      hibernate:
        format_sql: true  # Format SQL output
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Hibernate dialect for PostgreSQL

  data:
    web:
      pageable:
        default-page-size: 20  # Default page size for pagination
        max-page-size: 100  # Maximum page size for pagination

logging:
  level:
    org.utku.shoppingapi: INFO  # Log level for application classes
    org.springframework.web: DEBUG  # Log level for Spring web
    org.hibernate.SQL: DEBUG  # Log level for Hibernate SQL
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # Console log pattern
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"  # File log pattern
  file:
    name: logs/shopping-api.log  # Log file location

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics  # Expose health, info, and metrics endpoints
  endpoint:
    health:
      show-details: when-authorized  # Show health details only when authorized

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs  # Path for OpenAPI docs
  swagger-ui:
    path: /swagger-ui.html  # Path for Swagger UI
    operations-sorter: alpha  # Sort operations alphabetically
    tags-sorter: alpha  # Sort tags alphabetically
    try-it-out-enabled: true  # Enable Try It Out feature
    filter: true  # Enable filtering in Swagger UI
    display-request-duration: true  # Show request duration

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}  # Secret key for JWT
  expiration: ${JWT_EXPIRATION:86400000}  # JWT expiration time (default: 24 hours)
